version: '2'
services:

  scraper:
    build:
      context: .
      dockerfile: docker/scraper/Dockerfile
    environment:
      - CDMS_USERNAME
      - CDMS_PASSWORD
      - CDMS_ADFS_URL
      - CDMS_BASE_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3CACHE_BUCKET
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
      - ES_HOST=elasticsearch
      - ES PORT=9200
      - ES_INDEX=odata
    command: /app/start.sh
    links:
      - redis
      - elasticsearch

  redis:
    image: redis:3.2
    restart: always
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:5.2
    restart: always
    ports:
      - "9200:9200"
